export const GET_PRODUCT_DETAIL_REQUEST = 'GET_PRODUCT_DETAIL_REQUEST';
export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS';
export const GET_PRODUCT_DETAIL_FAIL = 'GET_PRODUCT_DETAIL_FAIL';

export const GET_PRODUCT_STYLE_REQUEST = 'GET_PRODUCT_STYLE_REQUEST';
export const GET_PRODUCT_STYLE_SUCCESS = 'GET_PRODUCT_STYLE_SUCCESS';
export const GET_PRODUCT_STYLE_FAIL = 'GET_PRODUCT_STYLE_FAIL';

export const GET_PRODUCT_REVIEW_METADATA_REQUEST =
  'GET_PRODUCT_REVIEW_METADATA_REQUEST';
export const GET_PRODUCT_REVIEW_METADATA_SUCCESS =
  'GET_PRODUCT_REVIEW_METADATA_SUCCESS';
export const GET_PRODUCT_REVIEW_METADATA_FAIL =
  'GET_PRODUCT_REVIEW_METADATA_FAIL';

export const ADD_ITEM_TO_CART_REQUEST = 'ADD_ITEM_TO_CART_REQUEST';
export const ADD_ITEM_TO_CART_SUCCESS = 'ADD_ITEM_TO_CART_SUCCESS';
export const ADD_ITEM_TO_CART_FAIL = 'ADD_ITEM_TO_CART_FAIL';

export const GET_PRODUCT_QUESTION_REQUEST = 'GET_PRODUCT_QUESTION_REQUEST';
export const GET_PRODUCT_QUESTION_SUCCESS = 'GET_PRODUCT_QUESTION_SUCCESS';
export const GET_PRODUCT_QUESTION_FAIL = 'GET_PRODUCT_QUESTION_FAIL';

export const GET_PRODUCT_REVIEWS_REQUEST = 'GET_PRODUCT_REVIEWS_REQUEST';
export const GET_PRODUCT_REVIEWS_SUCCESS = 'GET_PRODUCT_REVIEWS_SUCCESS';
export const GET_PRODUCT_REVIEWS_FAIL = 'GET_PRODUCT_REVIEWS_FAIL';

export const GET_RELATED_PRODUCTS_REQUEST = 'GET_RELATED_PRODUCTS_REQUEST';
export const GET_RELATED_PRODUCTS_SUCCESS = 'GET_RELATED_PRODUCTS_SUCCESS';
export const GET_RELATED_PRODUCTS_FAIL = 'GET_RELATED_PRODUCTS_FAIL';

export const GET_RELATED_DETAILS_REQUEST = 'GET_RELATED_DETAILS_REQUEST';
export const GET_RELATED_DETAILS_SUCCESS = 'GET_RELATED_DETAILS_SUCCESS';
export const GET_RELATED_DETAILS_FAIL = 'GET_RELATED_DETAILS_FAIL';

export const GET_RELATED_STYLE_REQUEST = 'GET_RELATED_STYLE_REQUEST';
export const GET_RELATED_STYLE_SUCCESS = 'GET_RELATED_STYLE_SUCCESS';
export const GET_RELATED_STYLE_FAIL = 'GET_RELATED_STYLE_FAIL';
