export const GET_PRODUCT_DETAIL_REQUEST = 'GET_PRODUCT_DETAIL_REQUEST';
export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS';
export const GET_PRODUCT_DETAIL_FAIL = 'GET_PRODUCT_DETAIL_FAIL';

export const GET_PRODUCT_STYLE_REQUEST = 'GET_PRODUCT_STYLE_REQUEST';
export const GET_PRODUCT_STYLE_SUCCESS = 'GET_PRODUCT_STYLE_SUCCESS';
export const GET_PRODUCT_STYLE_FAIL = 'GET_PRODUCT_STYLE_FAIL';

export const GET_PRODUCT_REVIEW_METADATA_REQUEST =
  'GET_PRODUCT_REVIEW_METADATA_REQUEST';
export const GET_PRODUCT_REVIEW_METADATA_SUCCESS =
  'GET_PRODUCT_REVIEW_METADATA_SUCCESS';
export const GET_PRODUCT_REVIEW_METADATA_FAIL =
  'GET_PRODUCT_REVIEW_METADATA_FAIL';

export const GET_RELATED_PRODUCTS_REQUEST = 'GET_RELATED_PRODUCTS_REQUEST';
export const GET_RELATED_PRODUCTS_SUCCESS = 'GET_RELATED_PRODUCTS_SUCCESS';
export const GET_RELATED_PRODUCTS_FAIL = 'GET_RELATED_PRODUCTS_FAIL';